name: Build
on:
  - push
  - pull_request

jobs:
  build-python:
    uses: goes-funky/workflows/.github/workflows/build-python.yaml@master
    with:
      python-version: "3.9"
      is-repo-public: true
      skip-mypy: true
      skip-tests: true
      skip-isort: true
      skip-format: true
      skip-lint: true
    secrets:
      ssh-private-key: ${{ secrets.GH_REPO_READ_SSH_KEY }}